#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
build_v7.py - Generate GPT-Image-2 prompt search engine HTML
Strategy: HTML loads JSON data from external files via fetch()
This avoids all JS string escaping nightmares
"""

import json, os

BASE = r'C:\Users\Administrator\WorkBuddy\2026-05-31-10-53-55\gpt-image-prompts'
DATA = os.path.join(BASE, 'data')
IMG_DIR = os.path.join(BASE, 'images')

# Read data
with open(os.path.join(DATA, 'cases-full.json'), 'r', encoding='utf-8') as f:
    cases_data = json.load(f)

with open(os.path.join(DATA, 'templates.json'), 'r', encoding='utf-8') as f:
    tpl_data = json.load(f)

cases = cases_data.get('cases', [])
templates = tpl_data if isinstance(tpl_data, list) else tpl_data.get('templates', [])

print(f'Cases: {len(cases)}, Templates: {len(templates)}')

# Check local images
have_imgs = set()
missing_404 = set()
if os.path.exists(IMG_DIR):
    for fname in os.listdir(IMG_DIR):
        if fname.startswith('case') and fname.endswith('.jpg') and not fname.endswith('.missing'):
            try:
                have_imgs.add(int(fname[4:-4]))
            except ValueError:
                pass
        elif fname.endswith('.jpg.missing'):
            try:
                missing_404.add(int(fname[4:-11]))
            except (ValueError, IndexError):
                pass

print(f'Local images: {len(have_imgs)}, 404: {len(missing_404)}')

# Pre-process: add image availability flags to cases
# We'll write a simplified cases array to a separate JS data file
simple_cases = []
for c in cases:
    cid = c['id']
    simple_cases.append({
        'id': cid,
        't': c.get('title', ''),
        'p': c.get('prompt', ''),
        'pp': c.get('promptPreview', ''),
        'c': c.get('category', ''),
        's': c.get('styles', []),
        'sc': c.get('scenes', []),
        'f': c.get('featured', False),
        'h': cid in have_imgs,
        'nf': cid in missing_404,
    })

# Write data.js (external data file - no escaping issues!)
js_content = f'''// GPT-Image-2 Prompt Search Engine - Data File
// Auto-generated by build_v7.py

var CASES_META = {json.dumps(simple_cases, ensure_ascii=False, separators=(',',':'))};

var TEMPLATES = {json.dumps(templates, ensure_ascii=False, separators=(',',':'))};
'''

js_path = os.path.join(BASE, 'data.js')
with open(js_path, 'w', encoding='utf-8') as f:
    f.write(js_content)

js_sz = os.path.getsize(js_path)
print(f'Generated data.js: {js_sz/1024:.1f} KB')

# Now generate the HTML (loads data.js as a regular <script> tag - no escaping needed!)
html = r"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GPT-Image-2 提示词搜索引擎</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
:root{
  --bg:#0f0f23;--bg2:#1a1a2e;--bg3:#25253e;
  --accent:#7c5cfc;--accent2:#a78bfa;--green:#34d399;
  --text:#e2e8f0;--text2:#94a3b8;--border:#2d2d4a;
  --radius:12px;
}
body{font-family:-apple-system,'Segoe UI',sans-serif;background:var(--bg);color:var(--text);min-height:100vh;}

.header{background:var(--bg2);border-bottom:1px solid var(--border);padding:12px 20px;display:flex;align-items:center;gap:12px;position:sticky;top:0;z-index:100;flex-wrap:wrap;}
.logo{font-size:18px;font-weight:800;background:linear-gradient(135deg,var(--accent),#f472b6);-webkit-background-clip:text;-webkit-text-fill-color:transparent;white-space:nowrap;}
.search-box{flex:1;max-width:540px;position:relative;}
.search-box .si{position:absolute;left:12px;top:50%;transform:translateY(-50%);color:var(--text2);font-size:13px;pointer-events:none;}
.search-box input{width:100%;padding:8px 12px 8px 34px;background:var(--bg3);border:1px solid var(--border);border-radius:20px;color:var(--text);font-size:13px;outline:none;transition:all .2s;}
.search-box input:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(124,92,252,.15);}
.stats{font-size:11px;color:var(--text2);white-space:nowrap;}
.mode-toggle{display:flex;background:var(--bg3);border-radius:8px;padding:2px;gap:2px;}
.mode-toggle button{padding:5px 11px;border:none;border-radius:6px;background:transparent;color:var(--text2);font-size:12px;cursor:pointer;transition:all .2s;}
.mode-toggle button.active{background:var(--accent);color:#fff;font-weight:600;}

.filters{background:var(--bg2);border-bottom:1px solid var(--border);padding:8px 20px;display:flex;gap:10px;flex-wrap:wrap;align-items:center;}
.fg{display:flex;align-items:center;gap:5px;}
.fg label{font-size:11px;color:var(--text2);white-space:nowrap;}
.fg select{padding:4px 20px 4px 8px;background:var(--bg3);border:1px solid var(--border);border-radius:6px;color:var(--text);font-size:12px;cursor:pointer;appearance:none;-webkit-appearance:none;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='5'%3E%3Cpath d='M0 0l4 5 4-5z' fill='%2394a3b8'/%3E%3C/svg%3E");background-repeat:no-repeat;background-position:right 6px center;}
.fg select:focus{outline:none;border-color:var(--accent);}
.chip{padding:3px 10px;border-radius:14px;border:1px solid var(--border);background:var(--bg3);color:var(--text2);font-size:11px;cursor:pointer;transition:all .2s;user-select:none;}
.chip.active{background:var(--accent);color:#fff;border-color:var(--accent);}

.container{max-width:1440px;margin:0 auto;padding:20px;}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(290px,1fr));gap:16px;}
.card{background:var(--bg2);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;transition:all .25s;cursor:pointer;display:flex;flex-direction:column;}
.card:hover{border-color:var(--accent);transform:translateY(-3px);box-shadow:0 8px 28px rgba(124,92,252,.15);}
.ciw{width:100%;height:200px;overflow:hidden;background:var(--bg3);display:flex;align-items:center;justify-content:center;position:relative;}
.ciw img{width:100%;height:100%;object-fit:cover;display:block;}
.ciw .noimg{text-align:center;color:var(--text2);font-size:12px;padding:8px;}
.cb{padding:10px 12px 12px;flex:1;display:flex;flex-direction:column;}
.ct{font-size:12px;font-weight:600;margin-bottom:4px;line-height:1.4;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;}
.cm{display:flex;gap:3px;flex-wrap:wrap;margin-bottom:5px;}
.tag{padding:1px 5px;border-radius:4px;font-size:10px;line-height:1.7;}
.tag.cat{background:rgba(124,92,252,.15);color:var(--accent2);}
.tag.stl{background:rgba(52,211,153,.12);color:var(--green);}
.cp{font-size:11px;color:var(--text2);line-height:1.5;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;margin-bottom:6px;flex:1;}
.ca{display:flex;gap:5px;margin-top:auto;}
.btn-copy{flex:1;padding:4px 8px;border-radius:6px;border:1px solid var(--accent);background:transparent;color:var(--accent);font-size:10px;cursor:pointer;transition:all .2s;text-align:center;}
.btn-copy:hover{background:var(--accent);color:#fff;}
.btn-view{padding:4px 8px;border-radius:6px;border:1px solid var(--border);background:transparent;color:var(--text2);font-size:10px;cursor:pointer;transition:all .2s;}
.btn-view:hover{border-color:var(--accent);color:var(--accent);}

.empty{text-align:center;padding:60px 20px;color:var(--text2);display:none;}
.empty .ic{font-size:40px;margin-bottom:12px;}
.empty p{font-size:14px;}

/* Modal */
.mo{display:none;position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.88);z-index:1000;overflow-y:auto;}
.mo.open{display:flex;align-items:flex-start;justify-content:center;padding:30px 16px;}
.modal{background:var(--bg2);border-radius:var(--radius);max-width:900px;width:100%;overflow:hidden;margin-bottom:30px;}
.miw{width:100%;max-height:460px;overflow:hidden;background:#000;display:flex;align-items:center;justify-content:center;}
.miw img{width:100%;height:auto;max-height:460px;object-fit:contain;display:block;}
.miw .noimg-m{color:var(--text2);padding:30px;text-align:center;font-size:13px;}
.mb{padding:18px 20px 20px;}
.mt2{font-size:17px;font-weight:700;margin-bottom:10px;line-height:1.4;}
.mm{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px;}
.mp{background:var(--bg3);border-radius:8px;padding:13px;font-size:12px;line-height:1.7;color:var(--text);white-space:pre-wrap;word-break:break-all;max-height:360px;overflow-y:auto;font-family:'Courier New',monospace;margin-bottom:12px;}
.ma{display:flex;gap:10px;}
.bp{padding:7px 16px;border-radius:8px;border:none;background:var(--accent);color:#fff;font-size:13px;font-weight:600;cursor:pointer;transition:all .2s;}
.bp:hover{opacity:.88;}
.bs{padding:7px 16px;border-radius:8px;border:1px solid var(--border);background:transparent;color:var(--text);font-size:13px;cursor:pointer;}

@media(max-width:768px){
  .header{padding:10px 12px;gap:8px;}
  .search-box{max-width:100%;order:3;width:100%;}
  .grid{grid-template-columns:1fr;}
}
</style>
</head>
<body>

<div class="header">
  <div class="logo">GPT-Image-2 提示词库</div>
  <div class="search-box">
    <span class="si">🔍</span>
    <input type="text" id="searchInput" placeholder="搜索提示词、标题、分类、风格..." oninput="onSearchInput(this.value)" />
  </div>
  <div class="stats" id="stats"></div>
  <div class="mode-toggle">
    <button id="btnCase" class="active" onclick="switchMode('case')">🖼️ 案例 (<span id="caseCnt">""" + str(len(cases)) + r"""</span>)</button>
    <button id="btnTpl" onclick="switchMode('tpl')">📋 模板 (<span id="tplCnt">""" + str(len(templates)) + r"""</span>)</button>
  </div>
</div>

<div class="filters">
  <div class="fg" id="fgCat">
    <label>分类：</label>
    <select id="catFilter" onchange="doRender()">
      <option value="">全部分类</option>
    </select>
  </div>
  <div class="fg" id="fgStyle" style="display:none">
    <label>风格：</label>
    <select id="styleFilter" onchange="doRender()">
      <option value="">全部风格</option>
    </select>
  </div>
  <div class="fg" id="fgScene" style="display:none">
    <label>场景：</label>
    <select id="sceneFilter" onchange="doRender()">
      <option value="">全部场景</option>
    </select>
  </div>
  <label class="chip" id="chipFeatured" onclick="toggleFeatured()">⭐ 精选</label>
</div>

<div class="container">
  <div class="grid" id="grid"></div>
  <div class="empty" id="emptyDiv">
    <div class="ic">😕</div>
    <p>没有找到匹配的结果，换个关键词试试？</p>
  </div>
</div>

<!-- Modal -->
<div class="mo" id="modal" onclick="closeModal(event)">
  <div class="modal" onclick="event.stopPropagation()">
    <div class="miw" id="modalImgWrap"></div>
    <div class="mb">
      <div class="mt2" id="modalTitle"></div>
      <div class="mm" id="modalMeta"></div>
      <div class="mp" id="modalPrompt"></div>
      <div class="ma">
        <button class="bp" onclick="doCopy()">📋 复制提示词</button>
        <button class="bs" onclick="closeModal()">关闭</button>
      </div>
    </div>
  </div>
</div>

<script src="data.js"></script>
<script>
// ===== State =====
var currentMode = 'case';
var showFeatured = false;
var currentPrompt = '';
var searchTimer = null;

// ===== Init =====
function init() {
  if (typeof CASES_META === 'undefined') {
    document.getElementById('stats').textContent = '数据加载失败，请确保 data.js 在同目录下';
    return;
  }
  // Categories
  var cats = [...new Set(CASES_META.map(function(c){return c.c}))].sort();
  var cs = document.getElementById('catFilter');
  cats.forEach(function(c){
    var o = document.createElement('option');
    o.value = c; o.textContent = c;
    cs.appendChild(o);
  });
  // Styles
  var styles = [...new Set(CASES_META.flatMap(function(c){return c.s||[]}))].sort();
  var ss = document.getElementById('styleFilter');
  styles.forEach(function(s){
    var o = document.createElement('option');
    o.value = s; o.textContent = s;
    ss.appendChild(o);
  });
  document.getElementById('fgStyle').style.display = '';
  // Scenes
  var scenes = [...new Set(CASES_META.flatMap(function(c){return c.sc||[]}))].sort();
  var scs = document.getElementById('sceneFilter');
  scenes.forEach(function(s){
    var o = document.createElement('option');
    o.value = s; o.textContent = s;
    scs.appendChild(o);
  });
  document.getElementById('fgScene').style.display = '';
  doRender();
}

// ===== Helpers =====
function escHtml(s) {
  if (!s) return '';
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function getImgSrc(item) {
  if (item.h) return 'images/case' + item.id + '.jpg';
  // 404 or no image: SVG placeholder as data URI
  var svg = '<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300">' +
    '<rect width="400" height="300" fill="%231a1a2e"/>' +
    '<text x="200" y="120" text-anchor="middle" fill="%237c5cfc" font-size="38" font-weight="bold">#' + item.id + '</text>' +
    '<text x="200" y="165" text-anchor="middle" fill="%23888" font-size="13">图片缺失 / 404</text>' +
    '<text x="200" y="195" text-anchor="middle" fill="%23666" font-size="11">' + escHtml(item.t||'').substring(0,24) + '</text>' +
    '</svg>';
  return 'data:image/svg+xml,' + encodeURIComponent(svg);
}

// ===== Render =====
function doRender() {
  var grid = document.getElementById('grid');
  var emptyDiv = document.getElementById('emptyDiv');
  var kw = (document.getElementById('searchInput').value||'').toLowerCase().trim();
  var cat = document.getElementById('catFilter').value;
  var style = document.getElementById('styleFilter').value;
  var scene = document.getElementById('sceneFilter').value;

  var list = (currentMode === 'case') ? CASES_META.slice() : TEMPLATES.slice();

  if (currentMode === 'case') {
    if (cat) list = list.filter(function(c){return c.c === cat;});
    if (style) list = list.filter(function(c){return (c.s||[]).indexOf(style)!==-1;});
    if (scene) list = list.filter(function(c){return (c.sc||[]).indexOf(scene)!==-1;});
    if (showFeatured) list = list.filter(function(c){return c.f;});
  }

  if (kw) {
    list = list.filter(function(item) {
      var text = [];
      if (currentMode === 'case') {
        text.push(item.t||'');
        text.push(item.p||'');
        text.push(item.c||'');
        text.push((item.s||[]).join(' '));
        text.push((item.sc||[]).join(' '));
      } else {
        text.push(item.title||item.name||'');
        text.push(item.prompt||item.template||'');
        text.push((item.tags||item.category||[]).join(' '));
        text.push(item.description||'');
      }
      return text.join(' ').toLowerCase().indexOf(kw) !== -1;
    });
  }

  var MAX = 200;
  var showing = list.slice(0, MAX);
  var trimmed = list.length > MAX;

  var total = (currentMode === 'case') ? CASES_META.length : TEMPLATES.length;
  var statsTxt = '找到 ' + list.length + ' / ' + total + ' 条';
  if (trimmed) statsTxt += '（仅显示前' + MAX + '条，请缩小搜索范围）';
  document.getElementById('stats').textContent = statsTxt;

  if (showing.length === 0) {
    grid.innerHTML = '';
    emptyDiv.style.display = '';
    return;
  }
  emptyDiv.style.display = 'none';

  var parts = [];
  for (var i = 0; i < showing.length; i++) {
    var item = showing[i];
    if (currentMode === 'case') {
      var imgSrc = getImgSrc(item);
      var isDataUri = imgSrc.substring(0,5) === 'data';
      var imgHtml;
      if (isDataUri) {
        imgHtml = '<div class="noimg">图片缺失</div>';
      } else {
        imgHtml = '<img src="' + escHtml(imgSrc) + '" alt="' + escHtml(item.t) + '" loading="lazy" onerror="this.style.display=\'none\';this.nextElementSibling.style.display=\'block\';" /><div class="noimg" style="display:none">图片加载失败</div>';
      }
      parts.push(
        '<div class="card" onclick="openCase(' + item.id + ')">' +
          '<div class="ciw">' + imgHtml + '</div>' +
          '<div class="cb">' +
            '<div class="ct">#' + item.id + ' ' + escHtml(item.t) + '</div>' +
            '<div class="cm">' +
              '<span class="tag cat">' + escHtml(item.c) + '</span>' +
              (item.s||[]).slice(0,2).map(function(s){return '<span class="tag stl">' + escHtml(s) + '</span>';}).join('') +
            '</div>' +
            '<div class="cp">' + escHtml((item.pp||item.p||'').substring(0,100)) + '</div>' +
            '<div class="ca">' +
              '<button class="btn-copy" onclick="event.stopPropagation();doCopyId(' + item.id + ')">📋 复制</button>' +
              '<button class="btn-view" onclick="event.stopPropagation();openCase(' + item.id + ')">查看</button>' +
            '</div>' +
          '</div>' +
        '</div>'
      );
    } else {
      var title = item.title || item.name || '模板';
      var tags = item.tags || item.category || [];
      if (typeof tags === 'string') tags = [tags];
      parts.push(
        '<div class="card" onclick="openTpl(' + (item.id||0) + ')">' +
          '<div class="cb">' +
            '<div class="ct">📋 ' + escHtml(title) + '</div>' +
            '<div class="cm">' + tags.slice(0,3).map(function(t){return '<span class="tag cat">' + escHtml(t) + '</span>';}).join('') + '</div>' +
            '<div class="cp">' + escHtml((item.description||(item.prompt||'').substring(0,100))) + '</div>' +
            '<div class="ca">' +
              '<button class="btn-copy" onclick="event.stopPropagation();doCopyTpl(' + (item.id||0) + ')">📋 复制</button>' +
              '<button class="btn-view" onclick="event.stopPropagation();openTpl(' + (item.id||0) + ')">查看</button>' +
            '</div>' +
          '</div>' +
        '</div>'
      );
    }
  }
  grid.innerHTML = parts.join('');
}

// ===== Search =====
function onSearchInput(val) {
  clearTimeout(searchTimer);
  searchTimer = setTimeout(doRender, 150);
}

// ===== Mode =====
function switchMode(mode) {
  currentMode = mode;
  document.getElementById('btnCase').classList.toggle('active', mode==='case');
  document.getElementById('btnTpl').classList.toggle('active', mode==='tpl');
  document.getElementById('fgCat').style.display = mode==='case' ? '' : 'none';
  document.getElementById('fgStyle').style.display = mode==='case' ? '' : 'none';
  document.getElementById('fgScene').style.display = mode==='case' ? '' : 'none';
  document.getElementById('chipFeatured').style.display = mode==='case' ? '' : 'none';
  if (mode === 'tpl') {
    document.getElementById('catFilter').value = '';
    document.getElementById('styleFilter').value = '';
    document.getElementById('sceneFilter').value = '';
    showFeatured = false;
    document.getElementById('chipFeatured').classList.remove('active');
  }
  doRender();
}

function toggleFeatured() {
  showFeatured = !showFeatured;
  document.getElementById('chipFeatured').classList.toggle('active', showFeatured);
  doRender();
}

// ===== Modal =====
function openCase(id) {
  var item = CASES_META.find(function(c){return c.id === id;});
  if (!item) return;
  currentPrompt = item.p || '';
  var wrap = document.getElementById('modalImgWrap');
  if (item.h) {
    wrap.innerHTML = '<img src="images/case' + id + '.jpg" alt="' + escHtml(item.t) + '" onerror="this.style.display=\'none\';this.parentNode.querySelector(\'.noimg-m\').style.display=\'block\';" /><div class="noimg-m" style="display:none"><div style="font-size:32px;color:#7c5cfc;margin-bottom:8px">#' + id + '</div><div>图片加载失败</div></div>';
  } else {
    wrap.innerHTML = '<div class="noimg-m"><div style="font-size:32px;color:#7c5cfc;margin-bottom:8px">#' + id + '</div><div>图片缺失（服务器 404）</div><div style="font-size:11px;color:#666;margin-top:6px">' + escHtml(item.t) + '</div></div>';
  }
  document.getElementById('modalTitle').textContent = '#' + id + ' ' + (item.t || '');
  var metaHtml = '<span class="tag cat">' + escHtml(item.c) + '</span>';
  metaHtml += (item.s||[]).map(function(s){return '<span class="tag stl">' + escHtml(s) + '</span>';}).join('');
  metaHtml += (item.sc||[]).map(function(s){return '<span class="tag cat">' + escHtml(s) + '</span>';}).join('');
  if (item.f) metaHtml += '<span class="tag stl">⭐ 精选</span>';
  document.getElementById('modalMeta').innerHTML = metaHtml;
  document.getElementById('modalPrompt').textContent = item.p || '（无提示词）';
  document.getElementById('modal').classList.add('open');
}

function openTpl(id) {
  var item = TEMPLATES.find(function(t){return (t.id||0) === id;});
  if (!item) return;
  currentPrompt = item.prompt || item.template || '';
  var wrap = document.getElementById('modalImgWrap');
  wrap.innerHTML = '<div class="noimg-m"><div style="font-size:32px;margin-bottom:8px">📋</div><div>模板预览</div></div>';
  var title = item.title || item.name || '模板';
  document.getElementById('modalTitle').textContent = '📋 ' + title;
  var tags = item.tags || item.category || [];
  if (typeof tags === 'string') tags = [tags];
  document.getElementById('modalMeta').innerHTML = tags.slice(0,5).map(function(t){return '<span class="tag cat">' + escHtml(t) + '</span>';}).join('');
  document.getElementById('modalPrompt').textContent = item.prompt || item.template || '（无模板内容）';
  document.getElementById('modal').classList.add('open');
}

function closeModal(e) {
  if (e && e.target !== e.currentTarget) return;
  document.getElementById('modal').classList.remove('open');
}

function doCopy() {
  if (!currentPrompt) return;
  navigator.clipboard.writeText(currentPrompt).then(function(){
    var btn = document.querySelector('.bp');
    var orig = btn.textContent;
    btn.textContent = '✅ 已复制！';
    setTimeout(function(){btn.textContent=orig;},1200);
  }).catch(function(){alert('复制失败，请手动选中提示词后 Ctrl+C');});
}

function doCopyId(id) {
  var item = CASES_META.find(function(c){return c.id===id;});
  if (!item) return;
  var text = item.p || '';
  navigator.clipboard.writeText(text).then(function(){
    event.target.textContent = '✅ 已复制！';
    setTimeout(function(){event.target.textContent='📋 复制';},1200);
  }).catch(function(){alert('复制失败');});
}

function doCopyTpl(id) {
  var item = TEMPLATES.find(function(t){return (t.id||0)===id;});
  if (!item) return;
  var text = item.prompt || item.template || '';
  navigator.clipboard.writeText(text).then(function(){
    event.target.textContent = '✅ 已复制！';
    setTimeout(function(){event.target.textContent='📋 复制';},1200);
  }).catch(function(){alert('复制失败');});
}

// ===== Keyboard =====
document.addEventListener('keydown', function(e){
  if (e.key === 'Escape') closeModal();
  if (e.ctrlKey && e.key === 'f') { e.preventDefault(); document.getElementById('searchInput').focus(); }
});

// ===== Load data.js dynamically if not loaded =====
function loadData() {
  if (typeof CASES_META !== 'undefined') {
    init();
    return;
  }
  var s = document.createElement('script');
  s.src = 'data.js?t=' + Date.now();
  s.onload = init;
  s.onerror = function(){
    document.getElementById('stats').textContent = '数据加载失败，请确保 data.js 在同目录下';
  };
  document.head.appendChild(s);
}

loadData();
</script>
</body>
</html>"""

out_path = os.path.join(BASE, 'search-engine.html')
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(html)

sz = os.path.getsize(out_path)
print(f'\nGenerated: {out_path}')
print(f'  HTML size: {sz/1024:.1f} KB')
print(f'  data.js size: {js_sz/1024:.1f} KB')
print(f'  Total: {(sz+js_sz)/1024:.1f} KB')
print(f'  Cases with images: {sum(1 for c in simple_cases if c["h"])}')
print(f'  404 cases: {sum(1 for c in simple_cases if c["nf"])}')
print(f'  Templates: {len(templates)}')
